name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: xdebug
        
    - name: Setup WordPress test environment
      run: |
        bash bin/install-wp-tests.sh wordpress_test root '' localhost latest
        
    - name: Install dependencies
      run: |
        composer install
        
    - name: Run PHPCS
      run: |
        ./vendor/bin/phpcs
        
    - name: Run PHPUnit tests
      run: |
        ./vendor/bin/phpunit
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3